import { registerProvider } from '../registry';
import type { LocalMediaProvider } from '../contract';

export type SttMockInput = {
  text?: string;
  durationSec?: number;
};

export type SttMockOutput = {
  text: string;
  durationSec: number;
  timing: 'mock';
  providerStatus?: number;
};

export const sttMockProvider = registerProvider({
  id: 'stt.mock',
  kind: 'stt',
  tier: 'local',
  mode: 'local',
  displayName: 'Mock STT',
  estimateCost: () => ({ currency: 'USD', estimated: 0, actual: 0 }),
  actualCost: () => ({ currency: 'USD', estimated: 0, actual: 0 }),
  ledgerOutput(output) {
    const wordCount = output.text.trim().split(/\s+/).filter(Boolean).length;
    return { wordCount, segmentCount: Math.max(1, Math.ceil(wordCount / 28)), durationSec: output.durationSec, timing: output.timing };
  },
  async run(input) {
    const text = input.text ?? 'Placeholder transcript generated by the local mock STT provider.';
    return { text, durationSec: input.durationSec ?? 30, timing: 'mock' };
  }
} satisfies LocalMediaProvider<SttMockInput, SttMockOutput>);
