export { AssetSchema as AssetSchemaV3, AssetProvenanceSchema, VideoMetadataSchema, AudioMetadataSchema, type Asset as AssetV3 } from './assets/schema';
export { ClipSchema as ClipSchemaV3, TrackSchema as TrackSchemaV3, TrackFxSchema, type Clip as ClipV3, type Track as TrackV3 } from './tracks/schema';
export { OutputSchema as OutputSchemaV3, OutputRangeSchema as OutputRangeSchemaV3, AspectSchema, type Output as OutputV3 } from './outputs/schema';
export { OperationBaseSchema as OperationBaseSchemaV3, OperationStatusSchema as OperationStatusSchemaV3, OperationTargetSchema as OperationTargetSchemaV3, ClipSpanTargetSchema as ClipSpanTargetSchemaV3, ClipBoundaryTargetSchema as ClipBoundaryTargetSchemaV3, TrackTargetSchema as TrackTargetSchemaV3, type OperationBase as OperationBaseV3, type OperationTarget as OperationTargetV3, type ClipSpanTarget as ClipSpanTargetV3, type ClipBoundaryTarget as ClipBoundaryTargetV3, type TrackTarget as TrackTargetV3, type OperationKind, type OperationValidationContext, type PillView, type OverlayView } from './operations/base';
export { CutOperationSchema as CutOperationSchemaV3, cutOperationKind, type CutOperation as CutOperationV3 } from './operations/cut';
export { MuteOperationSchema as MuteOperationSchemaV3, muteOperationKind, type MuteOperation as MuteOperationV3 } from './operations/mute';
export { VoicePatchOperationSchema as VoicePatchOperationSchemaV3, voicePatchOperationKind, type VoicePatchOperation as VoicePatchOperationV3 } from './operations/voice-patch';
export { SpeedOperationSchema as SpeedOperationSchemaV3, speedOperationKind, type SpeedOperation as SpeedOperationV3 } from './operations/speed';
export { OverlayOperationSchema as OverlayOperationSchemaV3, overlayOperationKind, type OverlayOperation as OverlayOperationV3 } from './operations/overlay';
export { TransitionOperationSchema as TransitionOperationSchemaV3, transitionOperationKind, type TransitionOperation as TransitionOperationV3 } from './operations/transition';
export { CaptionStyleOperationSchema as CaptionStyleOperationSchemaV3, captionStyleOperationKind, type CaptionStyleOperation as CaptionStyleOperationV3 } from './operations/caption-style';
export { TranscriptAmendOperationSchema as TranscriptAmendOperationSchemaV3, transcriptAmendOperationKind, type TranscriptAmendOperation as TranscriptAmendOperationV3 } from './operations/transcript-amend';
export { OperationSchema as OperationSchemaV3, registeredOperationKinds, operationKindByType, getOperationKind, hasOperationKind, OPERATION_PRECEDENCE, type Operation as OperationV3 } from './operations/registry';
export { ManifestV3Schema, RenderPresetSchema as RenderPresetSchemaV3, RenderPresetsSchema as RenderPresetsSchemaV3, StudioCleanupSchema, AudioChannelFixSchema, type ManifestV3, type StudioCleanup, type AudioChannelFix } from './manifest/schema';
export { validateManifestV3Document, validateManifest, validateOperationOverlaps, operationPrecedence, type ManifestV3ValidationContext, type ManifestV3ValidationResult, type OverlapCandidate } from './manifest/validate';
export { addOperation, updateOperation, type OperationInput, type OperationPatch } from './manifest/apply';
export { type TimeMap, type TimeMapSegment } from './timeMap/types';
export { type ProviderRequestCostSummary, type ProviderRequestCostSummaryRow } from './providerRequests';
export { BRAND_PACKS, BrandPackSchema, BrandPackPreviewSchema, getBrandPack, isKnownBrandPackId, type BrandPack, type BrandPackPreviewKind } from './brand-packs/catalog';
export { setBrandPackId } from './brand-packs/operations';
export { buildBaseTimeline, composeTimeMap, outputTime as outputTimeV3, sourceTimeAt, outputRangeForClipSourceSpan } from './timeMap/compose';
export { type RenderStage, type OutputRange as RenderOutputRange, type OverlaySource, type Rect } from './render/types';
export { buildRenderPlan as buildRenderPlanV3, type V3RenderPlan, type RenderProfile, type TrackComposition } from './render/plan';
export { projectCaptions as projectCaptionsV3, captionsToSrt as captionsToSrtV3, captionsToVtt as captionsToVttV3, type V3CaptionCue } from './captions/project';
export { deriveEditedScriptFromTimeMap as deriveEditedScriptFromTimeMapV3, type V3EditedScript, type V3EditedScriptToken } from './transcript/edited-script';
export { derivePreviewScriptFromTimeMap as derivePreviewScriptFromTimeMapV3, type V3PreviewScript, type V3PreviewScriptToken, type V3PreviewScriptWordToken, type V3PreviewScriptReplacementToken } from './transcript/preview-script';
export { selectEnrollmentSentences, enrollmentCorpus, type EnrollmentSentence } from './enrollmentCorpus';
