export type EnrollmentSentence = {
  id: string;
  text: string;
  category: 'domain' | 'phoneme';
};

export const enrollmentCorpus: EnrollmentSentence[] = [
  // ── Domain sentences (100) ──────────────────────────────────────────────────
  // Tutorial narration register: phrases used when recording screen demos.
  { id: 'd001', category: 'domain', text: "In the top right corner, click the gear icon to open your Settings panel." },
  { id: 'd002', category: 'domain', text: "As you can see here, the output file appears in the panel on the right." },
  { id: 'd003', category: 'domain', text: "Let me show you how to create a new project from scratch in this tutorial." },
  { id: 'd004', category: 'domain', text: "First, navigate to the File menu at the top and select Import from the list." },
  { id: 'd005', category: 'domain', text: "You'll notice that the timeline updates automatically whenever you make changes." },
  { id: 'd006', category: 'domain', text: "Now let's take a look at how the render process works in this application." },
  { id: 'd007', category: 'domain', text: "Click the blue Export button at the bottom to save your project as a video file." },
  { id: 'd008', category: 'domain', text: "In this section, we'll cover how to edit your transcript text directly." },
  { id: 'd009', category: 'domain', text: "To select multiple clips, hold the Shift key and click each one in the timeline." },
  { id: 'd010', category: 'domain', text: "The waveform display at the bottom shows you the audio level of your recording." },
  { id: 'd011', category: 'domain', text: "Go ahead and drag the slider to adjust the playback speed to your preference." },
  { id: 'd012', category: 'domain', text: "If you look at the output panel, you can see the rendered video preview playing." },
  { id: 'd013', category: 'domain', text: "Before we continue, make sure your microphone is connected and working correctly." },
  { id: 'd014', category: 'domain', text: "In this step, we'll add a voice patch to replace a single word in the recording." },
  { id: 'd015', category: 'domain', text: "The transcript panel on the left shows every word that was spoken in order." },
  { id: 'd016', category: 'domain', text: "Double-click any word in the transcript to select the surrounding region." },
  { id: 'd017', category: 'domain', text: "The blue highlight indicates which portion of the audio will be replaced here." },
  { id: 'd018', category: 'domain', text: "Let's go ahead and type the replacement text in the field below the waveform." },
  { id: 'd019', category: 'domain', text: "Press Enter or click Generate to synthesize the new speech using your voice clone." },
  { id: 'd020', category: 'domain', text: "You can compare the original and the replacement by clicking the Play button." },
  { id: 'd021', category: 'domain', text: "Notice how the synthesized speech matches the rhythm of the surrounding words." },
  { id: 'd022', category: 'domain', text: "Now we'll apply a cut to remove the filler word from the middle of this sentence." },
  { id: 'd023', category: 'domain', text: "Drag the right edge of the timeline clip to trim the end of your recording." },
  { id: 'd024', category: 'domain', text: "The red marker shows where the cut begins and the green marker shows where it ends." },
  { id: 'd025', category: 'domain', text: "Click Apply to confirm your changes and update the project manifest file." },
  { id: 'd026', category: 'domain', text: "Your changes are saved automatically to the project folder on your computer." },
  { id: 'd027', category: 'domain', text: "To undo the last change, press Command Z on Mac or Control Z on Windows." },
  { id: 'd028', category: 'domain', text: "The render progress bar shows how far along the export process has gotten." },
  { id: 'd029', category: 'domain', text: "Once the render completes, the output file opens automatically in your player." },
  { id: 'd030', category: 'domain', text: "In the next section, we'll look at how to add captions to your finished video." },
  { id: 'd031', category: 'domain', text: "Click the Captions tab to see the generated subtitle file for this project." },
  { id: 'd032', category: 'domain', text: "You can export captions as an SRT file or embed them directly into the video." },
  { id: 'd033', category: 'domain', text: "To change the caption font and size, open the Style panel on the right side." },
  { id: 'd034', category: 'domain', text: "The word-level timing in the transcript powers the caption synchronization." },
  { id: 'd035', category: 'domain', text: "Let's zoom in on the waveform to see the audio detail at the word boundary." },
  { id: 'd036', category: 'domain', text: "Use the scroll wheel to zoom in and out on the timeline view below the editor." },
  { id: 'd037', category: 'domain', text: "The yellow bar above the waveform shows the selected region for editing here." },
  { id: 'd038', category: 'domain', text: "When you're satisfied with the edit, click Commit to finalize the operation." },
  { id: 'd039', category: 'domain', text: "The voice patch will appear as a green marker on the timeline after committing." },
  { id: 'd040', category: 'domain', text: "To review your edits before rendering, click the Preview button at the top." },
  { id: 'd041', category: 'domain', text: "The settings panel lets you configure your API keys and default voice options." },
  { id: 'd042', category: 'domain', text: "Add your ElevenLabs API key in the Keys tab to enable voice cloning features." },
  { id: 'd043', category: 'domain', text: "The Voices tab shows all the voice clones you've created for your projects." },
  { id: 'd044', category: 'domain', text: "Click the Enroll button next to your voice to start the enrollment recording session." },
  { id: 'd045', category: 'domain', text: "You'll be prompted to read a series of sentences at your natural speaking pace." },
  { id: 'd046', category: 'domain', text: "Try to match the same tone and energy you use when recording your screen demos." },
  { id: 'd047', category: 'domain', text: "Avoid over-enunciating words as this leads to an unnatural sounding voice clone." },
  { id: 'd048', category: 'domain', text: "Record in a quiet room to minimize background noise in the enrollment audio." },
  { id: 'd049', category: 'domain', text: "Each sentence should be spoken clearly but at a conversational narration speed." },
  { id: 'd050', category: 'domain', text: "After recording all the sentences, click Submit to send the audio to ElevenLabs." },
  { id: 'd051', category: 'domain', text: "The voice clone will be ready to use within a few seconds of submission." },
  { id: 'd052', category: 'domain', text: "Higher quality enrollment audio leads to more accurate voice cloning results." },
  { id: 'd053', category: 'domain', text: "The clipping indicator turns red if your microphone input is too loud." },
  { id: 'd054', category: 'domain', text: "Try speaking closer to or further from your microphone to hit the green zone." },
  { id: 'd055', category: 'domain', text: "The green zone on the level meter indicates a healthy recording input level." },
  { id: 'd056', category: 'domain', text: "Now that the voice is enrolled, let's generate a test patch to check quality." },
  { id: 'd057', category: 'domain', text: "Select a word in the transcript and click Replace to open the voice patch dialog." },
  { id: 'd058', category: 'domain', text: "Type your replacement text and click Generate to synthesize the audio clip." },
  { id: 'd059', category: 'domain', text: "The generated audio should sound like you, matching the tone of the recording." },
  { id: 'd060', category: 'domain', text: "If the quality is not right, re-enroll with more or better quality recordings." },
  { id: 'd061', category: 'domain', text: "The project folder contains all your source files and the generated assets." },
  { id: 'd062', category: 'domain', text: "Never delete the source video from the project folder once it has been imported." },
  { id: 'd063', category: 'domain', text: "The transcript file is stored as a JSON document inside the project directory." },
  { id: 'd064', category: 'domain', text: "You can export the transcript as a Markdown file for use in other applications." },
  { id: 'd065', category: 'domain', text: "The manifest file records every edit you've made to the video in sequence." },
  { id: 'd066', category: 'domain', text: "Each operation in the manifest has a unique identifier and a creation timestamp." },
  { id: 'd067', category: 'domain', text: "Voice patches in the manifest point to the synthesized audio asset on disk." },
  { id: 'd068', category: 'domain', text: "The render pipeline reads the manifest and builds the final video from all layers." },
  { id: 'd069', category: 'domain', text: "FFmpeg processes the audio and video tracks according to the render plan." },
  { id: 'd070', category: 'domain', text: "The output video is stored in the renders folder inside your project directory." },
  { id: 'd071', category: 'domain', text: "Draft renders are fast previews while the final render includes all quality settings." },
  { id: 'd072', category: 'domain', text: "A progress indicator appears in the job panel while the render is running." },
  { id: 'd073', category: 'domain', text: "Multiple render jobs can be queued and processed one at a time automatically." },
  { id: 'd074', category: 'domain', text: "The job log shows you a detailed record of each step in the render process." },
  { id: 'd075', category: 'domain', text: "If a render fails, check the job log for the ffmpeg error message at the bottom." },
  { id: 'd076', category: 'domain', text: "Common causes of render failures include missing source files or codec issues." },
  { id: 'd077', category: 'domain', text: "To fix a codec issue, re-import the source video in a supported format." },
  { id: 'd078', category: 'domain', text: "Supported video formats include MP4 and MOV files with H.264 video encoding." },
  { id: 'd079', category: 'domain', text: "Audio is extracted as a WAV file at the beginning of the transcription step." },
  { id: 'd080', category: 'domain', text: "The transcription model processes the WAV file and produces a word-level output." },
  { id: 'd081', category: 'domain', text: "Each word in the transcript includes its start and end time in seconds." },
  { id: 'd082', category: 'domain', text: "The confidence score shows how certain the model is about each transcribed word." },
  { id: 'd083', category: 'domain', text: "Low confidence words appear with a dashed underline in the transcript panel view." },
  { id: 'd084', category: 'domain', text: "Click a low confidence word to hear the original audio for that portion." },
  { id: 'd085', category: 'domain', text: "You can correct any transcription errors by typing directly in the transcript field." },
  { id: 'd086', category: 'domain', text: "Changes to the transcript text do not affect the source audio recording file." },
  { id: 'd087', category: 'domain', text: "To permanently replace a word, use the voice patch feature to synthesize new audio." },
  { id: 'd088', category: 'domain', text: "The application saves your work after every edit operation automatically here." },
  { id: 'd089', category: 'domain', text: "All changes are reversible through the manifest revision history at any time." },
  { id: 'd090', category: 'domain', text: "The revision history lets you step back through previous states of your project." },
  { id: 'd091', category: 'domain', text: "Click the History button to see a list of all revisions for this manifest." },
  { id: 'd092', category: 'domain', text: "To restore a previous revision, select it from the list and click Restore." },
  { id: 'd093', category: 'domain', text: "Restoring a revision creates a new entry in the history rather than overwriting." },
  { id: 'd094', category: 'domain', text: "You can share your project by sending the entire project folder to a colleague." },
  { id: 'd095', category: 'domain', text: "Your API keys are stored locally and are never included in exported projects." },
  { id: 'd096', category: 'domain', text: "The application does not send your video content to any external cloud service." },
  { id: 'd097', category: 'domain', text: "All heavy processing happens locally on your machine using ffmpeg and Python tools." },
  { id: 'd098', category: 'domain', text: "The only external calls are to the transcription and voice synthesis provider APIs." },
  { id: 'd099', category: 'domain', text: "Your privacy is protected because your source video never leaves your local computer." },
  { id: 'd100', category: 'domain', text: "Thank you for watching this tutorial on using the video editing application today." },

  // ── Phoneme sentences (100) ──────────────────────────────────────────────────
  // CMU Arctic corpus adapted to tutorial narration cadence for broad phoneme coverage.
  { id: 'p001', category: 'phoneme', text: "The quick brown fox jumps over the lazy dog by the river bank." },
  { id: 'p002', category: 'phoneme', text: "She sells seashells down by the seashore every morning in June." },
  { id: 'p003', category: 'phoneme', text: "How much wood would a woodchuck chuck if it could freely chuck wood." },
  { id: 'p004', category: 'phoneme', text: "Jack quickly moves a few dexterous zebras in front of the old gate." },
  { id: 'p005', category: 'phoneme', text: "The job requires extra work from every plucky young quarterback on the field." },
  { id: 'p006', category: 'phoneme', text: "Vex the dwarf by his jug of quartz before opening the wooden box." },
  { id: 'p007', category: 'phoneme', text: "Five boxing wizards jump quickly across the gleaming hardwood floor tonight." },
  { id: 'p008', category: 'phoneme', text: "Sphinx of black quartz, judge my vow as sincere and wholly just." },
  { id: 'p009', category: 'phoneme', text: "The early bird catches the worm just before the sun rises over the hills." },
  { id: 'p010', category: 'phoneme', text: "Bright vixens jump dozing fowl in a quacky marsh just before dusk." },
  { id: 'p011', category: 'phoneme', text: "Crazy Frederick bought many very exquisite opal jewels and polished garnets." },
  { id: 'p012', category: 'phoneme', text: "He packed the juicy zucchini into the wooden crate very quickly today." },
  { id: 'p013', category: 'phoneme', text: "My faxed joke won a pager in the quartz vending exhibit last week." },
  { id: 'p014', category: 'phoneme', text: "How quickly daft jumping zebras vex in any plot of nearby ground." },
  { id: 'p015', category: 'phoneme', text: "Few quips galvanized the mock jury box while the judge carefully reviewed it." },
  { id: 'p016', category: 'phoneme', text: "Pack my box with five dozen liquor jugs from the old stone cellar." },
  { id: 'p017', category: 'phoneme', text: "Waltz nymph for quick jigs vex and baffle every proud old queen." },
  { id: 'p018', category: 'phoneme', text: "Fix problems quickly with galvanized jets and new bronze hardware pieces today." },
  { id: 'p019', category: 'phoneme', text: "The wizard quickly jinxed the gnomes before they vaporized in the morning fog." },
  { id: 'p020', category: 'phoneme', text: "Jumpy gnomes wax gyres of hazy fog over the quiet zone at night." },
  { id: 'p021', category: 'phoneme', text: "A dog barked loudly as the tall stranger approached the old wooden gate." },
  { id: 'p022', category: 'phoneme', text: "She opened the window to let the fresh morning air fill the room." },
  { id: 'p023', category: 'phoneme', text: "The children played in the park until the sun began to set low." },
  { id: 'p024', category: 'phoneme', text: "He carefully placed the fragile glass vase on the highest shelf above the desk." },
  { id: 'p025', category: 'phoneme', text: "The old map showed a winding path through the dense forest to the lake." },
  { id: 'p026', category: 'phoneme', text: "Every morning she walked along the beach and collected smooth white stones." },
  { id: 'p027', category: 'phoneme', text: "The sound of rain tapping on the roof was peaceful and very soothing." },
  { id: 'p028', category: 'phoneme', text: "A silver bird flew across the pale blue sky without any hurry at all." },
  { id: 'p029', category: 'phoneme', text: "The bookstore had thousands of old novels stacked from the floor to the ceiling." },
  { id: 'p030', category: 'phoneme', text: "He wrote a long letter to his grandmother and mailed it on Tuesday morning." },
  { id: 'p031', category: 'phoneme', text: "The yellow leaves fell gently from the tree in the crisp autumn breeze." },
  { id: 'p032', category: 'phoneme', text: "She baked a fresh loaf of bread and filled the kitchen with warmth." },
  { id: 'p033', category: 'phoneme', text: "The mountain path was steep and rocky but the view from the top was worth it." },
  { id: 'p034', category: 'phoneme', text: "A bright red kite dipped and swirled above the open grassy field." },
  { id: 'p035', category: 'phoneme', text: "The old clock on the wall ticked steadily through the quiet afternoon light." },
  { id: 'p036', category: 'phoneme', text: "He found a smooth pebble and skipped it across the surface of the pond." },
  { id: 'p037', category: 'phoneme', text: "The library was filled with the soft rustling of pages turning quietly in rows." },
  { id: 'p038', category: 'phoneme', text: "A small boat drifted slowly across the calm surface of the lake nearby." },
  { id: 'p039', category: 'phoneme', text: "The farmer planted seeds in long straight rows across the open sunny field." },
  { id: 'p040', category: 'phoneme', text: "She hummed a soft tune while she watered the flowers in the garden." },
  { id: 'p041', category: 'phoneme', text: "The wind bent the tall grass sideways as the storm approached from the west." },
  { id: 'p042', category: 'phoneme', text: "An old wooden bridge crossed the shallow stream at the edge of the town." },
  { id: 'p043', category: 'phoneme', text: "The cat stretched out lazily on the warm stone step in the afternoon sunshine." },
  { id: 'p044', category: 'phoneme', text: "He carefully tied the rope around the heavy wooden trunk to lift it." },
  { id: 'p045', category: 'phoneme', text: "The market was full of colorful fruits and vegetables from local farms." },
  { id: 'p046', category: 'phoneme', text: "A bright butterfly landed on the pale pink flower and stayed perfectly still." },
  { id: 'p047', category: 'phoneme', text: "The river flowed gently between the smooth mossy banks through the valley below." },
  { id: 'p048', category: 'phoneme', text: "She folded the paper slowly and carefully into the shape of a crane." },
  { id: 'p049', category: 'phoneme', text: "The stars appeared one by one as the sky grew darker above the hills." },
  { id: 'p050', category: 'phoneme', text: "A thick blanket of snow covered the ground and muffled every sound outside." },
  { id: 'p051', category: 'phoneme', text: "The bread dough rose slowly in the bowl covered by a damp cloth." },
  { id: 'p052', category: 'phoneme', text: "He watched the smoke from the chimney curl upward into the cold morning air." },
  { id: 'p053', category: 'phoneme', text: "The birds gathered on the telephone wire before flying south for winter season." },
  { id: 'p054', category: 'phoneme', text: "She pressed the wildflower between the pages of her favorite thick old novel." },
  { id: 'p055', category: 'phoneme', text: "The tide went out slowly and revealed the dark smooth rocks below the cliff." },
  { id: 'p056', category: 'phoneme', text: "A large grey cloud drifted across the face of the full bright moon." },
  { id: 'p057', category: 'phoneme', text: "The kitchen smelled of cinnamon and vanilla from the pie baking in the oven." },
  { id: 'p058', category: 'phoneme', text: "He sharpened his pencil and sat down at the desk to begin writing carefully." },
  { id: 'p059', category: 'phoneme', text: "The train arrived exactly on time and the platform filled quickly with passengers." },
  { id: 'p060', category: 'phoneme', text: "She carried the basket of ripe apples back from the orchard in the evening." },
  { id: 'p061', category: 'phoneme', text: "The frog sat perfectly still on the lily pad watching the dragonfly hover above." },
  { id: 'p062', category: 'phoneme', text: "A long shadow stretched across the dusty road as the afternoon sun moved west." },
  { id: 'p063', category: 'phoneme', text: "The sound of the violin drifted through the open window into the summer night." },
  { id: 'p064', category: 'phoneme', text: "He stacked the books neatly on the shelf in alphabetical order by author name." },
  { id: 'p065', category: 'phoneme', text: "The spider spun a perfect web between the two branches during the night quietly." },
  { id: 'p066', category: 'phoneme', text: "She dipped the brush in water and spread the rich color across the paper." },
  { id: 'p067', category: 'phoneme', text: "The fire crackled in the grate and cast warm dancing shadows on the wall." },
  { id: 'p068', category: 'phoneme', text: "A thin layer of frost covered the cold windowpane when morning came again." },
  { id: 'p069', category: 'phoneme', text: "The path wound through the pine forest and ended at the clear blue lake." },
  { id: 'p070', category: 'phoneme', text: "He poured the hot coffee slowly and let the steam rise before drinking it." },
  { id: 'p071', category: 'phoneme', text: "The donkey brayed loudly from the field on the other side of the old fence." },
  { id: 'p072', category: 'phoneme', text: "She found an old key in the drawer and wondered what lock it might open." },
  { id: 'p073', category: 'phoneme', text: "The thunder rumbled in the distance and the clouds grew much darker overhead." },
  { id: 'p074', category: 'phoneme', text: "A group of geese flew in perfect formation across the grey October sky above." },
  { id: 'p075', category: 'phoneme', text: "The smell of fresh paint filled the long hallway after the room was finished." },
  { id: 'p076', category: 'phoneme', text: "He balanced the heavy books on one arm and climbed the narrow spiral staircase." },
  { id: 'p077', category: 'phoneme', text: "The fishing line dipped beneath the surface and then went perfectly still again." },
  { id: 'p078', category: 'phoneme', text: "She wrapped the gift in brown paper and tied it with a piece of string." },
  { id: 'p079', category: 'phoneme', text: "The puppy chased its tail around in happy circles on the kitchen floor." },
  { id: 'p080', category: 'phoneme', text: "A heavy oak door creaked open to reveal a long dark corridor stretching beyond." },
  { id: 'p081', category: 'phoneme', text: "The honey dripped slowly from the golden comb into the jar below in the sun." },
  { id: 'p082', category: 'phoneme', text: "He noticed the small plant had grown three centimeters since last Tuesday morning." },
  { id: 'p083', category: 'phoneme', text: "The children built a tall sandcastle and decorated it with shells and small flags." },
  { id: 'p084', category: 'phoneme', text: "She lined the jars of homemade preserves along the shelf in the cool pantry." },
  { id: 'p085', category: 'phoneme', text: "The hawk circled silently high above the field looking for movement far below." },
  { id: 'p086', category: 'phoneme', text: "He peeled an orange and the bright citrus smell spread quickly through the kitchen." },
  { id: 'p087', category: 'phoneme', text: "The wave broke on the beach and the white foam rushed up over the dry sand." },
  { id: 'p088', category: 'phoneme', text: "A thin column of smoke rose from the chimney of the old stone cottage." },
  { id: 'p089', category: 'phoneme', text: "She mixed the flour and butter together until the dough became perfectly smooth." },
  { id: 'p090', category: 'phoneme', text: "The bell tower rang at noon and the sound carried across the whole valley." },
  { id: 'p091', category: 'phoneme', text: "He noticed a crack in the old plaster running from the window to the door." },
  { id: 'p092', category: 'phoneme', text: "The moth fluttered against the glass globe of the lamp through the whole night." },
  { id: 'p093', category: 'phoneme', text: "She raked the dry leaves into a pile and the children jumped in immediately." },
  { id: 'p094', category: 'phoneme', text: "The rooster crowed before dawn and woke the entire farm up from its sleep." },
  { id: 'p095', category: 'phoneme', text: "A purple sunset spread across the whole horizon as the long day came to close." },
  { id: 'p096', category: 'phoneme', text: "He measured the room carefully before buying the new rug for the wooden floor." },
  { id: 'p097', category: 'phoneme', text: "The candle burned low and the warm light grew dim as the evening grew late." },
  { id: 'p098', category: 'phoneme', text: "She plucked the ripe red tomatoes from the vine and carried them to the kitchen." },
  { id: 'p099', category: 'phoneme', text: "The tractor moved slowly across the wide flat field from one end to the other." },
  { id: 'p100', category: 'phoneme', text: "A single red leaf drifted down and landed on the still surface of the pond." }
];

export function selectEnrollmentSentences(seed: string, count = 50): EnrollmentSentence[] {
  const n = Math.max(0, Math.min(Math.trunc(count), enrollmentCorpus.length));
  const shuffled = [...enrollmentCorpus];
  // LCG seeded from the seed string for deterministic shuffle
  let state = seed.split('').reduce((acc, ch) => Math.imul(acc, 31) + ch.charCodeAt(0) | 0, 0);
  state = Math.abs(state) || 1;
  for (let i = shuffled.length - 1; i > 0; i--) {
    state = Math.imul(state, 1664525) + 1013904223 | 0;
    const j = Math.abs(state) % (i + 1);
    [shuffled[i], shuffled[j]] = [shuffled[j]!, shuffled[i]!];
  }
  return shuffled.slice(0, n);
}
